#!/usr/bin/env python
# encoding: utf-8
"""
pe2.py

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.

Created by Adrian on 2010-09-15.
Copyright (c) 2010 __bullion__. All rights reserved.

"""

import sys
import os
import math


def main():
	sumOfAll =0
	top = 4000
	evensum = 2
	previous = 1
	current = 2
	sum = 0
	
	while sum < top:
		sum = current + previous
		previous = current
		if sum%2 == 0:
			evensum += sum
		
	print evensum

if __name__ == '__main__':
	main()